### ISSUE TITLE
2023赛季常规赛10月9日第二个半庄数据不正确

### ISSUE THREAD

**Issue by Vinceli2401** [Debonex/m-league-data-web#7]
Hello开发者, 
![WX20231227-122814@2x](https://github.com/Debonex/m-league-data-web/assets/62593369/3b7d2c50-c201-41f7-a880-4bac1831a2f8)
这条比赛数据不正确，正确的数据是：
堀慎吾8.8pt 铃木优+52pt 浅见真纪-14.4pt 菅原千瑛-46.4pt
劳烦改正一下，谢谢～

**Comment by Debonex** [comment]
已改正，多谢指正！
